#!/usr/bin/env bash

# DEPENDENCY DIRECTORY
DEP_DIR=deps/

# LINKS
RAYLIB_LINK="https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_linux_amd64.tar.gz"
TINY_FILE_DIALOG_LINK="https://sourceforge.net/projects/tinyfiledialogs/files/latest/download"
FONT_IOSEVKA_LINK="https://github.com/be5invis/Iosevka/releases/download/v33.2.7/PkgTTF-Iosevka-33.2.7.zip"

# FILE NAMING
RAYLIB_DIR=raylib
RAYLIB_TAR=raylib.tar.gz
RAYLIB_VER=raylib-5.5_linux_amd64

FONT_DIR=font

TINY_FILE_DIALOG_ZIP=tiny_file_dialog.zip

FONT_IOSEVKA_ZIP=PkgTTF-Iosevka-33.2.7.zip
echo "[INFO] DEPENDENCY DIR"
rm -rf "$DEP_DIR"
mkdir -p "$DEP_DIR"

echo "[INFO] CD INTO DEPENDENCY"
cd "$DEP_DIR"

echo "[INFO] RAYLIB"
wget -O "$RAYLIB_TAR" "$RAYLIB_LINK"
tar -xf "$RAYLIB_TAR"
mv "$RAYLIB_VER" "$RAYLIB_DIR"

echo "[INFO] TINY_FILE_DIALOG"
wget -O "$TINY_FILE_DIALOG_ZIP" "$TINY_FILE_DIALOG_LINK"
unzip "$TINY_FILE_DIALOG_ZIP"

echo "[INFO] FONT-DOWNLOADING"
wget "$FONT_IOSEVKA_LINK"
unzip "$FONT_IOSEVKA_ZIP"

echo "[INFO] MOVING FONTS TO DIR"
mkdir -p "$FONT_DIR"
mv *.ttf "$FONT_DIR"

# REMOVE GARBAGE FILES
rm -rf "$RAYLIB_TAR"
rm -rf "$TINY_FILE_DIALOG_ZIP"
rm -rf "$FONT_IOSEVKA_ZIP"
